apiVersion: v1
data:
  cachet-monitor-config.yml: |
    api:
      url: http://cachet-host:8080/api/v1
      token: TEST2
      insecure: false
    date_format: 02/01/2006 15:04:05 CET
    monitors:
      - name: Registry
        target: https://docker-registry.default.svc:5000/healthz
        strict: false
        method: GET
        component_id: 10
        #metrics:
        #    response_time: [ 74, 75 ]
        #metric_id: 72
        template:
          investigating:
            subject: "{{ .Monitor.Name }} - {{ .SystemName }}"
            message: "{{ .Monitor.Name }} check **failed** (server time: {{ .now }})\n\nThe Docker registry is not accessible inside the cluster."
          fixed:
            subject: "The Docker registry is accessible from inside the cluster."
        interval: 2
        timeout: 1
        resync: 60
        threshold: 50
        threshold_critical: 80
        expected_status_code: 200
        expected_body: "^$"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cachet-monitor-config
