apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: cachet-monitor
  name: cachet-monitor
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: cachet-monitor
    deploymentconfig: cachet-monitor
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: cachet-monitor
        deploymentconfig: cachet-monitor
    spec:
      containers:
      - image: docker-registry.default.svc:5000/openshift/cachet-monitor@sha256:33b1686ac312a39520bf885b81187663d8f3689ec0f906f106012f81cc751822
        imagePullPolicy: Always
        name: cachet-monitor
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 53
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/cachet-monitor/config
          name: cachet-monitor-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: cachet-monitor-config
        name: cachet-monitor-config
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - cachet-monitor
      from:
        kind: ImageStreamTag
        name: cachet-monitor:latest
        namespace: openshift
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
